/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as ApiCronHousekeepingRouteImport } from './routes/api/cron/housekeeping'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHousekeepingRoute = ApiCronHousekeepingRouteImport.update({
  id: '/api/cron/housekeeping',
  path: '/api/cron/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/support': typeof SupportRoute
  '/villkor': typeof VillkorRoute
  '/api/cron/housekeeping': typeof ApiCronHousekeepingRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/support': typeof SupportRoute
  '/villkor': typeof VillkorRoute
  '/api/cron/housekeeping': typeof ApiCronHousekeepingRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/support': typeof SupportRoute
  '/villkor': typeof VillkorRoute
  '/api/cron/housekeeping': typeof ApiCronHousekeepingRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integritet'
    | '/support'
    | '/villkor'
    | '/api/cron/housekeeping'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integritet'
    | '/support'
    | '/villkor'
    | '/api/cron/housekeeping'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/integritet'
    | '/support'
    | '/villkor'
    | '/api/cron/housekeeping'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegritetRoute: typeof IntegritetRoute
  SupportRoute: typeof SupportRoute
  VillkorRoute: typeof VillkorRoute
  ApiCronHousekeepingRoute: typeof ApiCronHousekeepingRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/housekeeping': {
      id: '/api/cron/housekeeping'
      path: '/api/cron/housekeeping'
      fullPath: '/api/cron/housekeeping'
      preLoaderRoute: typeof ApiCronHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegritetRoute: IntegritetRoute,
  SupportRoute: SupportRoute,
  VillkorRoute: VillkorRoute,
  ApiCronHousekeepingRoute: ApiCronHousekeepingRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
